"""add paper account high water mark

Revision ID: 0532a2465a95
Revises: 3974ddc6a822
Create Date: 2026-07-20 06:16:39.988876

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = '0532a2465a95'
down_revision: Union[str, None] = '3974ddc6a822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_accounts', sa.Column('high_water_mark', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_accounts', 'high_water_mark')
    # ### end Alembic commands ###
