"""initial schema

Revision ID: 3974ddc6a822
Revises: 
Create Date: 2026-07-20 06:01:49.598183

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types

revision: str = '3974ddc6a822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_accounts',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('masked_account_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('pip_size', sa.Float(), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('margin_rate', sa.Float(), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('notifications',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=15), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_settings',
    sa.Column('max_risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('max_same_symbol_positions', sa.Integer(), nullable=False),
    sa.Column('consecutive_loss_stop_count', sa.Integer(), nullable=False),
    sa.Column('max_spread_pips_default', sa.Float(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('live_trading_admin_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_mode', sa.String(length=15), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('context', app.db.types.PortableJSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_journals',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('source_ref_id', app.db.types.GUID(), nullable=True),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('signal_score', sa.Integer(), nullable=True),
    sa.Column('strategy_code', sa.String(length=50), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candles',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('granularity', sa.String(length=5), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'granularity', 'open_time', name='uq_candle_bucket')
    )
    op.create_index('ix_candle_lookup', 'candles', ['instrument_id', 'granularity', 'open_time'], unique=False)
    op.create_table('live_orders',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('broker_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_live_order_idem')
    )
    op.create_table('live_positions',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('broker_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_ticks',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tick_lookup', 'market_ticks', ['instrument_id', 'ts'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_configs',
    sa.Column('strategy_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', app.db.types.PortableJSON(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtests',
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('strategy_config_id', app.db.types.GUID(), nullable=False),
    sa.Column('config', app.db.types.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', app.db.types.PortableJSON(), nullable=False),
    sa.Column('equity_curve', app.db.types.PortableJSON(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_orders',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('account_id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_paper_order_idem')
    )
    op.create_table('paper_positions',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('account_id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('instrument_id', app.db.types.GUID(), nullable=False),
    sa.Column('strategy_config_id', app.db.types.GUID(), nullable=True),
    sa.Column('granularity', sa.String(length=5), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('regime_trend', sa.String(length=20), nullable=False),
    sa.Column('regime_volatility', sa.String(length=20), nullable=False),
    sa.Column('reasons', app.db.types.PortableJSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('backtest_id', app.db.types.GUID(), nullable=False),
    sa.Column('segment', sa.String(length=15), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('entry_reasons', app.db.types.PortableJSON(), nullable=False),
    sa.Column('exit_reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_trades')
    op.drop_table('signals')
    op.drop_table('paper_positions')
    op.drop_table('paper_orders')
    op.drop_table('backtests')
    op.drop_table('strategy_configs')
    op.drop_table('paper_accounts')
    op.drop_index('ix_tick_lookup', table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_table('live_positions')
    op.drop_table('live_orders')
    op.drop_index('ix_candle_lookup', table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trade_journals')
    op.drop_table('system_events')
    op.drop_table('strategies')
    op.drop_table('risk_settings')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('broker_accounts')
    # ### end Alembic commands ###
