"""add paper position opening idempotency key

Revision ID: dc1b9e1731d9
Revises: 0532a2465a95
Create Date: 2026-07-20 06:31:40.363786

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = 'dc1b9e1731d9'
down_revision: Union[str, None] = '0532a2465a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_positions', sa.Column('opening_idempotency_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_paper_positions_opening_idempotency_key'), 'paper_positions', ['opening_idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_positions_opening_idempotency_key'), table_name='paper_positions')
    op.drop_column('paper_positions', 'opening_idempotency_key')
    # ### end Alembic commands ###
