"""add audit_logs table

Revision ID: e27e8f12aa37
Revises: 62d7ff42a720
Create Date: 2026-07-21 01:19:06.762397

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = 'e27e8f12aa37'
down_revision: Union[str, None] = '62d7ff42a720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before', app.db.types.PortableJSON(), nullable=True),
    sa.Column('after', app.db.types.PortableJSON(), nullable=True),
    sa.Column('context', app.db.types.PortableJSON(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
